/**
 * docs.js — Renders MAP.md from the scored graph. Structure and numbers are
 * fully deterministic; LLM narration (if available) is inserted into clearly
 * marked sections so a reader can always tell derived fact from prose.
 */

import { narrateWorkflow, llmAvailable } from "../agents/llm.js";

const bar = (score) => {
  const n = Math.round(score * 10);
  return "█".repeat(n) + "░".repeat(10 - n);
};

/* ---- Mermaid rendering: every node/edge below is a graph fact ---- */

const mmId = (() => {
  const seen = new Map();
  return (label) => {
    if (!seen.has(label)) seen.set(label, `n${seen.size}`);
    return seen.get(label);
  };
})();
const mmLabel = (f) => f.replace(/"/g, "'");

const MERMAID_NODE_CAP = 30; // declared cap: beyond this a workflow gets a summary node, never a truncated-silently diagram

function mermaidOverview(graph) {
  const lines = ["```mermaid", "graph LR"];
  for (const wf of graph.workflows) {
    const e = mmId(`entry:${wf.id}`);
    const w = mmId(wf.id);
    lines.push(`  ${e}(["${mmLabel(wf.entry.kind)}: ${mmLabel(wf.entry.file)}"]) --> ${w}["${wf.files.length} files / ${wf.functionCount} fns<br/>confidence ${wf.confidence?.score ?? "?"}"]`);
  }
  if (graph.orphans.length) lines.push(`  ${mmId("orphans")}["orphans: ${graph.orphans.length} file(s)"]`);
  lines.push("```");
  return lines.join("\n");
}

function mermaidWorkflow(wf, graph) {
  const inWf = new Set(wf.files);
  const edges = graph.importEdges.filter((e) => e.to && inWf.has(e.from) && inWf.has(e.to));
  const lines = ["```mermaid", "graph LR"];
  if (wf.files.length > MERMAID_NODE_CAP) {
    lines.push(`  ${mmId(wf.id + ":big")}["${wf.files.length} files — exceeds ${MERMAID_NODE_CAP}-node diagram cap; see file list below"]`);
  } else {
    for (const f of wf.files) lines.push(`  ${mmId(wf.id + f)}["${mmLabel(f)}"]`);
    for (const e of edges) lines.push(`  ${mmId(wf.id + e.from)} --> ${mmId(wf.id + e.to)}`);
    if (!edges.length && wf.files.length === 1) lines.push(`  %% single-file workflow, no internal import edges`);
  }
  lines.push("```");
  return lines.join("\n");
}

export async function renderDocs(graph, { withNarration = true } = {}) {
  const s = graph.stats;
  const lines = [];
  lines.push(`# Project Map`);
  lines.push(``);
  lines.push(`> Generated by Map'd on ${graph.generatedAt} — every number below is derived from AST analysis, not estimated.`);
  lines.push(``);
  lines.push(`**Repo confidence: ${graph.repoConfidence}** (size-weighted composite across workflows)`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Files mapped | ${s.fileCount} (${s.totalLoc.toLocaleString()} LOC) |`);
  lines.push(`| Parsed cleanly | ${s.parsedCleanly} |`);
  lines.push(`| Parsed with recovery | ${s.parsedWithRecovery} |`);
  lines.push(`| Unparsed | ${s.unparsed} |`);
  lines.push(`| Unsupported-language files | ${s.unsupportedLanguageFiles} |`);
  lines.push(`| Import resolution rate | ${(s.importResolutionRate * 100).toFixed(1)}% |`);
  lines.push(`| Call resolution rate | ${(s.callResolutionRate * 100).toFixed(1)}% (${s.resolvedCalls}/${s.totalCalls}) |`);
  lines.push(``);

  lines.push(`## Topology`);
  lines.push(``);
  lines.push(mermaidOverview(graph));
  lines.push(``);
  lines.push(`## Workflows (${graph.workflows.length})`);
  lines.push(``);

  const narrate = withNarration && llmAvailable();

  for (const wf of graph.workflows) {
    const c = wf.confidence;
    lines.push(`### \`${wf.id}\``);
    lines.push(``);
    lines.push(`- **Entry:** \`${wf.entry.file}\` (${wf.entry.kind}: ${wf.entry.detail})`);
    lines.push(`- **Scope:** ${wf.files.length} files, ${wf.functionCount} functions`);
    lines.push(`- **Confidence:** \`${bar(c.score)}\` **${c.score}** (signal coverage ${c.signalCoverage})`);
    lines.push(``);
    lines.push(`| Signal | Value | Weight |`);
    lines.push(`|---|---|---|`);
    for (const [k, sig] of Object.entries(c.signals)) {
      lines.push(`| ${k} | ${sig.unavailable ? "unavailable" : sig.value} | ${sig.weight} |`);
    }
    lines.push(``);
    lines.push(mermaidWorkflow(wf, graph));
    lines.push(``);
    lines.push(`**Files:** ${wf.files.map((f) => `\`${f}\``).join(", ")}`);
    if (wf.exportedSurface.length) {
      lines.push(``);
      lines.push(`**Exported surface:** ${wf.exportedSurface.map((e) => `\`${e}\``).join(", ")}`);
    }
    if (narrate) {
      const prose = await narrateWorkflow(wf, s);
      if (prose) {
        lines.push(``);
        lines.push(`<!-- llm-narration: model-generated prose, structure above is ground truth -->`);
        lines.push(prose.trim());
      }
    }
    lines.push(``);
  }

  if (graph.orphans.length) {
    lines.push(`## Orphaned files (${graph.orphans.length})`);
    lines.push(``);
    lines.push(`Not reachable from any detected entry point — candidates for dead code or missing entry-point detection:`);
    lines.push(``);
    for (const f of graph.orphans) lines.push(`- \`${f}\``);
    lines.push(``);
  }

  if (graph.unsupported.length) {
    lines.push(`## Unmapped (no parser adapter yet)`);
    lines.push(``);
    for (const f of graph.unsupported) lines.push(`- \`${f}\``);
    lines.push(``);
  }

  return lines.join("\n");
}
